spring.application.name=productsApi

server.port=8080

# Configuração da Conexão com o Banco de Dados MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/ebac?useSSL=false&serverTimezone=UTC
spring.datasource.username=berdego
spring.datasource.password=berdego
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configurações do Hibernate / Spring Data JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
